no-permission-message: '&cYou do not have permission to execute that command.'
help-message: '&dsdf'
kits:
  Link:
  - ==: org.bukkit.inventory.ItemStack
    type: SHIELD
    meta:
      ==: ItemMeta
      meta-type: TILE_ENTITY
      display-name: §aHylian Shield
      lore:
      - Link's Shield
      ItemFlags: !!set
        HIDE_POTION_EFFECTS: null
      internal: H4sIAAAAAAAAAHWOMU7DQBBFf7Cx10ZQBA7ACahpECQkBRIhSOCOZmOP7VXs3bA7LjgJDR1cgVNQUHAhjAPIQWK60Xtf/8dAhOGI2apFwzQzmcoVWRcDGAj4V7ImDKf3jVrVpPnwRwgQjGrTaD7D+nxESXIxuSTp+OXxaf/55PXdQzRfkZWsjF474suZGcdvp8lHdjc/bituKsMITZ6XUmcCu79juu6DgjRZlR5JZpkuJ7KWBSHG3rgy6XKqWfHDrSwiiOvWIKu76YFA+P3DSxfGw/a5qYxtUYg+y6s+G/TZVln2kL+BmHtoZxO5f1N/dnjwx9JRp+ETbDt/LYkBAAA=
      blockMaterial: SHIELD
  PvP:
    - ==: org.bukkit.inventory.ItemStack
      type: WOOD_AXE
    - null
    - null
    - null
    - null
    - ==: org.bukkit.inventory.ItemStack
      type: STAINED_CLAY
      damage: 6
    - null
    - null
    - null
    - ==: org.bukkit.inventory.ItemStack
      type: STONE
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null