name: Test-SPIGOT-974
main: com.elmakers.mine.bukkit.plugins.test.UnitTestPlugin
version: 1.0
website: http://mine.elmakers.com
author: NathanWolf
description : A plugin to unit test the ArmorStand disabled slots API
commands:
  setslot:
    description: Configure an armor stand slot
    usage: |
        Use tab completion if you get lost
        /setslot <slot> <action> <disabled|enabled>
        /setslot hand remove disabled
        /setslot off_hand replace enabled
        /setslot feet place enabled
        /setslot legs replace enabled
        /setslot chest place disabled
        /setslot head place enabled
  spawnstand:
    description: Spawn an armor stand with arms
    usage: spawnstand