name: MultiExactCrafting
main: com.elmakers.mine.bukkit.plugins.test.crafting.UnitTestPlugin
version: 1.0
website: http://mine.elmakers.com
author: NathanWolf
description : A plugin to test multi-exact crafting
api-version: 1.16
