name: Magic-Damager
main: com.elmakers.mine.bukkit.plugins.test.MagicDamagerPlugin
version: 1.0
website: http://mine.elmakers.com
author: NathanWolf
description : A plugin to test Magic damage tracking
depends: Magic
commands: