name: Test-ItemMetaData
main: com.elmakers.mine.bukkit.plugins.test.UnitTestPlugin
version: 1.0
website: http://mine.elmakers.com
author: NathanWolf
description : A plugin to unit test Bukkit PRs
commands:
  soup:
    description: Get some stick soup
    usage: soup
    permission: soup
permissions:
  soup:
    description: Player may get some delicious stick soup
    type: boolean
    default: true