name: SPIGOT-6572
main: com.elmakers.mine.bukkit.plugins.test.UnitTestPlugin
version: 1.0
api-version: 1.14
author: NathanWolf
description: A plugin to unit test Spigot PRs and Issues
commands:
  checkentities:
    description: Check all loaded entities
    permission: checkentities
  spawnpersistent:
    description: Spawn a persistent villager
    permission: spawnpersistent
permissions:
  checkentities:
    default: op
  spawnpersistent:
    default: op
