name: SPIGOT-4234-Test
main: com.elmakers.mine.bukkit.plugins.test.UnitTestPlugin
version: 1.0
api-version: 1.15
website: http://mine.elmakers.com
author: NathanWolf
description : A plugin to unit test the PlayerSteerVehicleEvent
commands:
  broom:
    description: Mount a flying broomstick
    usage: broom
    permission: broom
permissions:
  broom:
    description: Player may fly on a broomstick
    type: boolean
    default: true