name: Test-AOECloud
main: com.elmakers.mine.bukkit.plugins.test.UnitTestPlugin
version: 1.0
website: http://mine.elmakers.com
author: NathanWolf
description : A plugin to test AOE cloud spawning
commands:
  cloud:
    description: Spawn an AOE cloud with redstone particles
    usage: cloud