name: Test-ItemMetaData
main: com.elmakers.mine.bukkit.plugins.test.UnitTestPlugin
version: 1.0
website: http://mine.elmakers.com
author: NathanWolf
description : A plugin to unit test Bukkit PRs
commands:
  launch:
    description: Launch a projectile
    usage: launch [type]
    permission: launch
  bow:
    description: Get a bow and 64 arrows
    usage: bow
    permission: bow
permissions:
  launch:
    description: Player may launch projectiles
    type: boolean
    default: true
  bow:
    description: Player may get a bow and arrows
    type: boolean
    default: true